function soma(num1, num2) {
    console.log(num1 + num2);
}
//Imprimir resultados
soma(10, 10);
soma(20, 20);

function divisao(num1, num2) {
    console.log(num1 / num2);
}
divisao(10, 10);
divisao(20, 10);

function multiplicacao(num1, num2) {
    console.log(num1 * num2);
}
multiplicacao(10, 10);
multiplicacao(20, 10);

function subtracao(num1, num2) {
    console.log(num1 - num2);
}
subtracao(10, 10);
subtracao(20, 10);
